//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIT_Solver {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class WebCEFSharp_Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static WebCEFSharp_Config defaultInstance = ((WebCEFSharp_Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WebCEFSharp_Config())));
        
        public static WebCEFSharp_Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CEFDATA_BORRAR_DATOS_AUTOMATICAMENTE {
            get {
                return ((bool)(this["CEFDATA_BORRAR_DATOS_AUTOMATICAMENTE"]));
            }
            set {
                this["CEFDATA_BORRAR_DATOS_AUTOMATICAMENTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CEFDATA_SEMANAS_PARA_BORRAR {
            get {
                return ((int)(this["CEFDATA_SEMANAS_PARA_BORRAR"]));
            }
            set {
                this["CEFDATA_SEMANAS_PARA_BORRAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CEFDATA_ULTIMO_BORRADO_DE_CACHE {
            get {
                return ((global::System.DateTime)(this["CEFDATA_ULTIMO_BORRADO_DE_CACHE"]));
            }
            set {
                this["CEFDATA_ULTIMO_BORRADO_DE_CACHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CEFDATA_PROXIMO_BORRADO {
            get {
                return ((global::System.DateTime)(this["CEFDATA_PROXIMO_BORRADO"]));
            }
            set {
                this["CEFDATA_PROXIMO_BORRADO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("es")]
        public string CEFDATA_DEFAULT_LANGUAGE {
            get {
                return ((string)(this["CEFDATA_DEFAULT_LANGUAGE"]));
            }
            set {
                this["CEFDATA_DEFAULT_LANGUAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("es-ES")]
        public string WEBVIEW2_DEFAULT_LANGUAGE {
            get {
                return ((string)(this["WEBVIEW2_DEFAULT_LANGUAGE"]));
            }
            set {
                this["WEBVIEW2_DEFAULT_LANGUAGE"] = value;
            }
        }
    }
}
