//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow_Solver.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailUsuarioIDC {
            get {
                return ((string)(this["EmailUsuarioIDC"]));
            }
            set {
                this["EmailUsuarioIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailPasswordIDC {
            get {
                return ((string)(this["EmailPasswordIDC"]));
            }
            set {
                this["EmailPasswordIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoDeReporte {
            get {
                return ((string)(this["NoDeReporte"]));
            }
            set {
                this["NoDeReporte"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Refacciones {
            get {
                return ((string)(this["Refacciones"]));
            }
            set {
                this["Refacciones"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NombreIDC {
            get {
                return ((string)(this["NombreIDC"]));
            }
            set {
                this["NombreIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalidadIDC {
            get {
                return ((string)(this["LocalidadIDC"]));
            }
            set {
                this["LocalidadIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProyectoIDC {
            get {
                return ((string)(this["ProyectoIDC"]));
            }
            set {
                this["ProyectoIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FotoIDCPath {
            get {
                return ((string)(this["FotoIDCPath"]));
            }
            set {
                this["FotoIDCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cliente {
            get {
                return ((string)(this["Cliente"]));
            }
            set {
                this["Cliente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Direccion {
            get {
                return ((string)(this["Direccion"]));
            }
            set {
                this["Direccion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CentroDeServicios {
            get {
                return ((string)(this["CentroDeServicios"]));
            }
            set {
                this["CentroDeServicios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailDestinoRefaccionesDefault {
            get {
                return ((string)(this["EmailDestinoRefaccionesDefault"]));
            }
            set {
                this["EmailDestinoRefaccionesDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LiderDeProyecto {
            get {
                return ((string)(this["LiderDeProyecto"]));
            }
            set {
                this["LiderDeProyecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RITFormPath {
            get {
                return ((string)(this["RITFormPath"]));
            }
            set {
                this["RITFormPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RITFormPathDestiny {
            get {
                return ((string)(this["RITFormPathDestiny"]));
            }
            set {
                this["RITFormPathDestiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FIRST_INITIALIZE {
            get {
                return ((bool)(this["FIRST_INITIALIZE"]));
            }
            set {
                this["FIRST_INITIALIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirmaIDCPath {
            get {
                return ((string)(this["FirmaIDCPath"]));
            }
            set {
                this["FirmaIDCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UsuarioDeRedIDC {
            get {
                return ((string)(this["UsuarioDeRedIDC"]));
            }
            set {
                this["UsuarioDeRedIDC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5.2.4")]
        public string SYS_VERSION {
            get {
                return ((string)(this["SYS_VERSION"]));
            }
            set {
                this["SYS_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24012024gAMMA")]
        public string SYS_ASSEMBLY {
            get {
                return ((string)(this["SYS_ASSEMBLY"]));
            }
            set {
                this["SYS_ASSEMBLY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string SYS_LAST_UPDATE {
            get {
                return ((string)(this["SYS_LAST_UPDATE"]));
            }
            set {
                this["SYS_LAST_UPDATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.129.175")]
        public string SERVER_ROUTE {
            get {
                return ((string)(this["SERVER_ROUTE"]));
            }
            set {
                this["SERVER_ROUTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_GUARDARRITENPDF {
            get {
                return ((bool)(this["SYSDATA_GUARDARRITENPDF"]));
            }
            set {
                this["SYSDATA_GUARDARRITENPDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ferromex2@scgenesis.mx")]
        public string EmailDistribuidorToner {
            get {
                return ((string)(this["EmailDistribuidorToner"]));
            }
            set {
                this["EmailDistribuidorToner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_UPDATES_ACTIVATE {
            get {
                return ((bool)(this["SYSDATA_UPDATES_ACTIVATE"]));
            }
            set {
                this["SYSDATA_UPDATES_ACTIVATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SYSDATA_INVENTORY_PATH {
            get {
                return ((string)(this["SYSDATA_INVENTORY_PATH"]));
            }
            set {
                this["SYSDATA_INVENTORY_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_FIRMA_HABILITADA {
            get {
                return ((bool)(this["SYSDATA_FIRMA_HABILITADA"]));
            }
            set {
                this["SYSDATA_FIRMA_HABILITADA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_BETA_UPDATES {
            get {
                return ((bool)(this["SYSDATA_BETA_UPDATES"]));
            }
            set {
                this["SYSDATA_BETA_UPDATES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_EXAMINAR_TONER_AUTOMATICO {
            get {
                return ((bool)(this["SYSDATA_EXAMINAR_TONER_AUTOMATICO"]));
            }
            set {
                this["SYSDATA_EXAMINAR_TONER_AUTOMATICO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RIT Solver Theme (Default)")]
        public string SYSDATA_TEMA_APLICADO {
            get {
                return ((string)(this["SYSDATA_TEMA_APLICADO"]));
            }
            set {
                this["SYSDATA_TEMA_APLICADO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SYS_CACHE_INVENTORY_LISTAUSUARIOS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SYS_CACHE_INVENTORY_LISTAUSUARIOS"]));
            }
            set {
                this["SYS_CACHE_INVENTORY_LISTAUSUARIOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActaResponsivaPath {
            get {
                return ((string)(this["ActaResponsivaPath"]));
            }
            set {
                this["ActaResponsivaPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_GUARDARRESGUARDOPDF {
            get {
                return ((bool)(this["SYSDATA_GUARDARRESGUARDOPDF"]));
            }
            set {
                this["SYSDATA_GUARDARRESGUARDOPDF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FIRST_INITIALIZE_INVENTORY {
            get {
                return ((bool)(this["FIRST_INITIALIZE_INVENTORY"]));
            }
            set {
                this["FIRST_INITIALIZE_INVENTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_GUARDARSIEMRPEINVENTARIO {
            get {
                return ((bool)(this["SYSDATA_GUARDARSIEMRPEINVENTARIO"]));
            }
            set {
                this["SYSDATA_GUARDARSIEMRPEINVENTARIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_OPEN_INVENTORY_ALWAYS_MAXIMIZE {
            get {
                return ((bool)(this["SYSDATA_OPEN_INVENTORY_ALWAYS_MAXIMIZE"]));
            }
            set {
                this["SYSDATA_OPEN_INVENTORY_ALWAYS_MAXIMIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100100")]
        public decimal RITCounter {
            get {
                return ((decimal)(this["RITCounter"]));
            }
            set {
                this["RITCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_DESCARGAR_E_INSTALAR_AUTOMATICAMENTE {
            get {
                return ((bool)(this["SYSDATA_DESCARGAR_E_INSTALAR_AUTOMATICAMENTE"]));
            }
            set {
                this["SYSDATA_DESCARGAR_E_INSTALAR_AUTOMATICAMENTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_CREAR_PROYECTO_BLANCO_AL_INICIAR {
            get {
                return ((bool)(this["SYSDATA_CREAR_PROYECTO_BLANCO_AL_INICIAR"]));
            }
            set {
                this["SYSDATA_CREAR_PROYECTO_BLANCO_AL_INICIAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_RECORDAR_ULTIMA_SESION {
            get {
                return ((bool)(this["SYSDATA_RECORDAR_ULTIMA_SESION"]));
            }
            set {
                this["SYSDATA_RECORDAR_ULTIMA_SESION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.ListDictionary SYSDATA_LOCALIDADES {
            get {
                return ((global::System.Collections.Specialized.ListDictionary)(this["SYSDATA_LOCALIDADES"]));
            }
            set {
                this["SYSDATA_LOCALIDADES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SYSDATA_LOCALIDAD_DEFAULT {
            get {
                return ((string)(this["SYSDATA_LOCALIDAD_DEFAULT"]));
            }
            set {
                this["SYSDATA_LOCALIDAD_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://forms.office.com/Pages/ResponsePage.aspx?id=dNF36JwJkUSX2NZVp8az1BdNDZCBA" +
            "PJHq77MIGUA38VUN0JXNUxNNkNSNVQxNlZHUDU3MkxHQUJQRS4u")]
        public string SYSDATA_URL_FORMS {
            get {
                return ((string)(this["SYSDATA_URL_FORMS"]));
            }
            set {
                this["SYSDATA_URL_FORMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://accounts.zoho.com/signin?servicename=SDPOnDemand&hide_title=true&hideyahoosignin=true&hidefbconnect=true&hide_secure=true&serviceurl=https%3A%2F%2Fsd.compusofmexico.com%2Fapp%2Fitdesk%2FHomePage.do&signupurl=https://sd.compusofmexico.com/AccountCreation.do&portal_id=142098036&hide_signup=true")]
        public string SYSDATA_URL_COMPUSOF {
            get {
                return ((string)(this["SYSDATA_URL_COMPUSOF"]));
            }
            set {
                this["SYSDATA_URL_COMPUSOF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gmxtsas.mx:8080/HomePage.do?view_type=my_view")]
        public string SYSDATA_URL_SERVICEDESK {
            get {
                return ((string)(this["SYSDATA_URL_SERVICEDESK"]));
            }
            set {
                this["SYSDATA_URL_SERVICEDESK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://endpointcentral.manageengine.com/webclient#/uems/home/smart-advisor")]
        public string SYSDATA_URL_ENDPOINT {
            get {
                return ((string)(this["SYSDATA_URL_ENDPOINT"]));
            }
            set {
                this["SYSDATA_URL_ENDPOINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_BACKGROUND_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["THEME_BACKGROUND_COLOR"]));
            }
            set {
                this["THEME_BACKGROUND_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_SECONDARY_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["THEME_SECONDARY_COLOR"]));
            }
            set {
                this["THEME_SECONDARY_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_TERTIARY_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["THEME_TERTIARY_COLOR"]));
            }
            set {
                this["THEME_TERTIARY_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_FOURSOME_COLOR {
            get {
                return ((global::System.Drawing.Color)(this["THEME_FOURSOME_COLOR"]));
            }
            set {
                this["THEME_FOURSOME_COLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_TEXT_PRIMARY {
            get {
                return ((global::System.Drawing.Color)(this["THEME_TEXT_PRIMARY"]));
            }
            set {
                this["THEME_TEXT_PRIMARY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color THEME_TEXT_SECONDARY {
            get {
                return ((global::System.Drawing.Color)(this["THEME_TEXT_SECONDARY"]));
            }
            set {
                this["THEME_TEXT_SECONDARY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CAN_CONTINUE_QUEST_INVENTORYPATH {
            get {
                return ((bool)(this["CAN_CONTINUE_QUEST_INVENTORYPATH"]));
            }
            set {
                this["CAN_CONTINUE_QUEST_INVENTORYPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SYSDATA_AutoSelectRecentSincModel {
            get {
                return ((bool)(this["SYSDATA_AutoSelectRecentSincModel"]));
            }
            set {
                this["SYSDATA_AutoSelectRecentSincModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SYSDATA_HabilitarMetodoDeImpresionSecundarioAutomaticamente {
            get {
                return ((bool)(this["SYSDATA_HabilitarMetodoDeImpresionSecundarioAutomaticamente"]));
            }
            set {
                this["SYSDATA_HabilitarMetodoDeImpresionSecundarioAutomaticamente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebView2")]
        public string SYSDATA_MetodoDeImpresionPorDefecto {
            get {
                return ((string)(this["SYSDATA_MetodoDeImpresionPorDefecto"]));
            }
            set {
                this["SYSDATA_MetodoDeImpresionPorDefecto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SYSDATA_ArchivosRITRecientes {
            get {
                return ((string)(this["SYSDATA_ArchivosRITRecientes"]));
            }
            set {
                this["SYSDATA_ArchivosRITRecientes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Publico\\Flow_Solver_server\\")]
        public string SYSDATA_DataBasePath {
            get {
                return ((string)(this["SYSDATA_DataBasePath"]));
            }
            set {
                this["SYSDATA_DataBasePath"] = value;
            }
        }
    }
}
